/* Generated by MyraPad at 16.10.2019 1:25:49 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace OpenSora.Viewer.UI
{
	partial class MainPanel: VerticalStackPanel
	{
		private void BuildUI()
		{
			_textPath = new TextBox();
			_textPath.Text = "";
			_textPath.Readonly = true;
			_textPath.Id = "_textPath";
			_textPath.Width = 300;

			_buttonChange = new TextButton();
			_buttonChange.Text = "Change...";
			_buttonChange.Id = "_buttonChange";

			var label1 = new Label();
			label1.Text = "Start";

			_numericAnimationStart = new SpinButton();
			_numericAnimationStart.Minimum = 0;
			_numericAnimationStart.Integer = true;
			_numericAnimationStart.Id = "_numericAnimationStart";
			_numericAnimationStart.Width = 32;

			var label2 = new Label();
			label2.Text = "Step";

			_numericAnimationStep = new SpinButton();
			_numericAnimationStep.Maximum = 8;
			_numericAnimationStep.Minimum = 0;
			_numericAnimationStep.Value = 8;
			_numericAnimationStep.Integer = true;
			_numericAnimationStep.Id = "_numericAnimationStep";
			_numericAnimationStep.Width = 32;

			_textAnimationTotal = new Label();
			_textAnimationTotal.Text = "Total: 64";
			_textAnimationTotal.Id = "_textAnimationTotal";

			_boxAnimation = new HorizontalStackPanel();
			_boxAnimation.Spacing = 8;
			_boxAnimation.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_boxAnimation.Id = "_boxAnimation";
			_boxAnimation.Widgets.Add(label1);
			_boxAnimation.Widgets.Add(_numericAnimationStart);
			_boxAnimation.Widgets.Add(label2);
			_boxAnimation.Widgets.Add(_numericAnimationStep);
			_boxAnimation.Widgets.Add(_textAnimationTotal);

			_buttonAbout = new TextButton();
			_buttonAbout.Text = "About";
			_buttonAbout.Id = "_buttonAbout";
			_buttonAbout.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			_boxTop = new HorizontalStackPanel();
			_boxTop.Spacing = 8;
			_boxTop.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_boxTop.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_boxTop.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			_boxTop.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			_boxTop.Id = "_boxTop";
			_boxTop.Widgets.Add(_textPath);
			_boxTop.Widgets.Add(_buttonChange);
			_boxTop.Widgets.Add(_boxAnimation);
			_boxTop.Widgets.Add(_buttonAbout);

			var listItem1 = new ListItem();
			listItem1.Id = null;
			listItem1.Text = "Textures";

			var listItem2 = new ListItem();
			listItem2.Id = null;
			listItem2.Text = "Models";

			var listItem3 = new ListItem();
			listItem3.Id = null;
			listItem3.Text = "Images";

			var listItem4 = new ListItem();
			listItem4.Id = null;
			listItem4.Text = "Animations";

			_comboResourceType = new ComboBox();
			_comboResourceType.Id = "_comboResourceType";
			_comboResourceType.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboResourceType.Items.Add(listItem1);
			_comboResourceType.Items.Add(listItem2);
			_comboResourceType.Items.Add(listItem3);
			_comboResourceType.Items.Add(listItem4);

			_textFilter = new TextBox();
			_textFilter.Text = "";
			_textFilter.Id = "_textFilter";

			var listItem5 = new ListItem();
			listItem5.Id = null;
			listItem5.Text = "TEXTURE1._DS";

			var listItem6 = new ListItem();
			listItem6.Id = null;
			listItem6.Text = "TEXTURE2._DS";

			_listFiles = new ListBox();
			_listFiles.Id = "_listFiles";
			_listFiles.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listFiles.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listFiles.Items.Add(listItem5);
			_listFiles.Items.Add(listItem6);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel1.Width = 150;
			verticalStackPanel1.Widgets.Add(_comboResourceType);
			verticalStackPanel1.Widgets.Add(_textFilter);
			verticalStackPanel1.Widgets.Add(_listFiles);

			_panelViewer = new Panel();
			_panelViewer.Id = "_panelViewer";

			_textStatus = new Label();
			_textStatus.Text = "Processing mesh 23/40...";
			_textStatus.Id = "_textStatus";
			_textStatus.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			var panel1 = new Panel();
			panel1.Widgets.Add(_panelViewer);
			panel1.Widgets.Add(_textStatus);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			horizontalStackPanel1.Widgets.Add(verticalStackPanel1);
			horizontalStackPanel1.Widgets.Add(panel1);

			
			Spacing = 8;
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Widgets.Add(_boxTop);
			Widgets.Add(horizontalStackPanel1);
		}

		
		public TextBox _textPath;
		public TextButton _buttonChange;
		public SpinButton _numericAnimationStart;
		public SpinButton _numericAnimationStep;
		public Label _textAnimationTotal;
		public HorizontalStackPanel _boxAnimation;
		public TextButton _buttonAbout;
		public HorizontalStackPanel _boxTop;
		public ComboBox _comboResourceType;
		public TextBox _textFilter;
		public ListBox _listFiles;
		public Panel _panelViewer;
		public Label _textStatus;
	}
}