/* Generated by MyraPad at 29.09.2019 1:41:46 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace OpenSora.Viewer.UI
{
	partial class MainPanel: VerticalBox
	{
		private void BuildUI()
		{
			var listItem1 = new ListItem();
			listItem1.Id = null;
			listItem1.Text = "Textures";

			var listItem2 = new ListItem();
			listItem2.Id = null;
			listItem2.Text = "Models";

			_comboResourceType = new ComboBox();
			_comboResourceType.Id = "_comboResourceType";
			_comboResourceType.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboResourceType.Items.Add(listItem1);
			_comboResourceType.Items.Add(listItem2);

			var listItem3 = new ListItem();
			listItem3.Id = null;
			listItem3.Text = "TEXTURE1._DS";

			var listItem4 = new ListItem();
			listItem4.Id = null;
			listItem4.Text = "TEXTURE2._DS";

			_listFiles = new ListBox();
			_listFiles.Id = "_listFiles";
			_listFiles.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listFiles.GridRow = 1;
			_listFiles.Items.Add(listItem3);
			_listFiles.Items.Add(listItem4);

			_panelViewer = new Panel();
			_panelViewer.Id = "_panelViewer";
			_panelViewer.GridColumn = 1;
			_panelViewer.GridRowSpan = 2;

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Proportion());
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.RowsProportions.Add(new Proportion());
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(_comboResourceType);
			grid1.Widgets.Add(_listFiles);
			grid1.Widgets.Add(_panelViewer);

			
			Spacing = 8;
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			Widgets.Add(grid1);
		}

		
		public ComboBox _comboResourceType;
		public ListBox _listFiles;
		public Panel _panelViewer;
	}
}