/* Generated by MyraPad at 08.06.2020 18:01:26 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace OpenSora.UI
{
	partial class CharacterTalkWidget: HorizontalStackPanel
	{
		private void BuildUI()
		{
			_imageCharacter = new Image();
			_imageCharacter.Id = "_imageCharacter";

			_labelName = new Label();
			_labelName.Text = "Estelle";
			_labelName.Id = "_labelName";

			_labelText = new Label();
			_labelText.Text = "Daddy's really late.";
			_labelText.Id = "_labelText";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel1.Widgets.Add(_labelName);
			verticalStackPanel1.Widgets.Add(_labelText);

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Width = 700;
			Height = 220;
			Background = new SolidBrush("#000000FF");
			Widgets.Add(_imageCharacter);
			Widgets.Add(verticalStackPanel1);
		}

		
		public Image _imageCharacter;
		public Label _labelName;
		public Label _labelText;
	}
}