/* Generated by MyraPad at 21.09.2019 23:45:05 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace OpenSora.Viewer.UI
{
	partial class MainPanel
	{
		private void BuildUI()
		{
			_textPath = new TextField();
			_textPath.Text = "";
			_textPath.Readonly = true;
			_textPath.Id = "_textPath";
			_textPath.Width = 300;

			_buttonChange = new TextButton();
			_buttonChange.Text = "Change...";
			_buttonChange.Id = "_buttonChange";
			_buttonChange.GridColumn = 1;

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Grid.Proportion());
			grid1.ColumnsProportions.Add(new Grid.Proportion());
			grid1.Widgets.Add(_textPath);
			grid1.Widgets.Add(_buttonChange);

			var listItem1 = new ListItem();
			listItem1.Id = null;
			listItem1.Text = "Textures";

			var listItem2 = new ListItem();
			listItem2.Id = null;
			listItem2.Text = "Models";

			_comboResourceType = new ComboBox();
			_comboResourceType.Id = "_comboResourceType";
			_comboResourceType.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboResourceType.Items.Add(listItem1);
			_comboResourceType.Items.Add(listItem2);

			var listItem3 = new ListItem();
			listItem3.Id = null;
			listItem3.Text = "TEXTURE1._DS";

			var listItem4 = new ListItem();
			listItem4.Id = null;
			listItem4.Text = "TEXTURE2._DS";

			_listFiles = new ListBox();
			_listFiles.Id = "_listFiles";
			_listFiles.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listFiles.GridRow = 1;
			_listFiles.Items.Add(listItem3);
			_listFiles.Items.Add(listItem4);

			_panelViewer = new Panel();
			_panelViewer.Id = "_panelViewer";
			_panelViewer.GridColumn = 1;
			_panelViewer.GridRowSpan = 2;

			var grid2 = new Grid();
			grid2.ColumnSpacing = 8;
			grid2.RowSpacing = 8;
			grid2.ColumnsProportions.Add(new Grid.Proportion());
			grid2.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid2.GridRow = 1;
			grid2.Widgets.Add(_comboResourceType);
			grid2.Widgets.Add(_listFiles);
			grid2.Widgets.Add(_panelViewer);

			var grid3 = new Grid();
			grid3.ColumnSpacing = 8;
			grid3.RowSpacing = 8;
			grid3.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid3.RowsProportions.Add(new Grid.Proportion());
			grid3.RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid3.Widgets.Add(grid1);
			grid3.Widgets.Add(grid2);

			
			Widgets.Add(grid3);
		}

		
		public TextField _textPath;
		public TextButton _buttonChange;
		public ComboBox _comboResourceType;
		public ListBox _listFiles;
		public Panel _panelViewer;
	}
}